
import type { CodingLevel } from '@/lib/types';

export const C_LEVELS: CodingLevel[] = [
  {
    title: 'Level 1: Hello, World!',
    description: 'The first step in any programming journey. Complete the code to print "Hello, World!" to the console.',
    concept: {
      title: 'Printing Output',
      explanation: 'In C, the `printf()` function is used to print text to the console. It\'s a fundamental way to see the result of your code. The text you want to print goes inside the parentheses and double quotes.',
    },
    codeTemplate: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    ',
      null,
      ';',
      '    return 0;',
      '}',
    ],
    options: [
      { id: 'c1-opt1', code: 'printf("Hello, World!");' },
      { id: 'c1-opt2', code: 'cout << "Hello, World!";' },
      { id: 'c1-opt3', code: 'print("Hello, World!");' },
    ],
    solution: ['c1-opt1'],
    blanks: 1,
  },
  {
    title: 'Level 2: Variables',
    description: 'Variables store data. Declare an integer variable named "age" and assign it the value 25.',
    concept: {
        title: 'Variables',
        explanation: 'Variables are containers for storing data values. In C, you must declare the type of the variable (like `int` for integers) before you use it. You can then assign a value to it using the `=` operator.',
    },
    codeTemplate: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    ',
      null,
      ';',
      '    printf("Age is: %d\\n", age);',
      '    return 0;',
      '}',
    ],
    options: [
      { id: 'c2-opt1', code: 'string age = "25"' },
      { id: 'c2-opt2', code: 'int age = 25' },
      { id: 'c2-opt3', code: 'let age = 25' },
    ],
    solution: ['c2-opt2'],
    blanks: 1,
  },
  {
    title: 'Level 3: For Loops',
    description: 'Loops repeat actions. Complete the `for` loop to count from 0 to 4.',
    concept: {
      title: 'For Loops',
      explanation: 'A `for` loop is used to repeat a block of code a specific number of times. It has three parts: initialization (runs once at the start), condition (checked before each run), and increment (runs after each run).',
    },
    codeTemplate: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    ',
      null,
      ' {',
      '        printf("%d\\n", i);',
      '    }',
      '    return 0;',
      '}',
    ],
    options: [
      { id: 'c3-opt1', code: 'for (int i = 0; i < 5; i++)' },
      { id: 'c3-opt2', code: 'loop(5)' },
      { id: 'c3-opt3', code: 'for i in range(5)' },
    ],
    solution: ['c3-opt1'],
    blanks: 1,
  },
  {
    title: 'Level 4: Conditional Statements',
    description: 'Use an `if-else` statement to check if a number is positive or non-positive.',
    concept: {
        title: 'If-Else Conditionals',
        explanation: '`if-else` statements allow your code to make decisions. The code inside the `if` block runs if a condition is true. Otherwise, the code inside the `else` block runs.',
    },
    codeTemplate: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int num = -5;',
      '    ',
      null,
      ' {',
      '        printf("Positive\\n");',
      '    } ',
      null,
      ' {',
      '        printf("Non-Positive\\n");',
      '    }',
      '    return 0;',
      '}',
    ],
    options: [
      { id: 'c4-opt1', code: 'if (num > 0)' },
      { id: 'c4-opt2', code: 'else' },
      { id: 'c4-opt3', code: 'if num > 0:' },
      { id: 'c4-opt4', code: 'otherwise' },
    ],
    solution: ['c4-opt1', 'c4-opt2'],
    blanks: 2,
  },
  {
    title: 'Level 5: Functions',
    description: 'Functions group code into reusable blocks. Call the `greet` function.',
    concept: {
        title: 'Functions',
        explanation: 'Functions are named blocks of code that perform a specific task. You can "call" a function to execute its code. This helps organize your program and avoids repeating code.',
    },
    codeTemplate: [
      '#include <stdio.h>',
      '',
      'void greet() {',
      '    printf("Greetings from a function!\\n");',
      '}',
      '',
      'int main() {',
      '    ',
      null,
      ';',
      '    return 0;',
      '}',
    ],
    options: [
      { id: 'c5-opt1', code: 'run greet()' },
      { id: 'c5-opt2', code: 'greet()' },
      { id: 'c5-opt3', code: 'call greet' },
    ],
    solution: ['c5-opt2'],
    blanks: 1,
  },
  {
    title: 'Level 6: Function with Parameters',
    description: 'Pass data to functions using parameters. Call `add` with two numbers.',
    concept: {
        title: 'Function Parameters',
        explanation: 'Parameters are like special variables for a function. They allow you to pass data into the function when you call it. The function can then use this data to perform its task.',
    },
    codeTemplate: [
        '#include <stdio.h>',
        '',
        'void add(int a, int b) {',
        '    printf("Sum: %d\\n", a + b);',
        '}',
        '',
        'int main() {',
        '    ',
        null,
        ';',
        '    return 0;',
        '}',
    ],
    options: [
        { id: 'c6-opt1', code: 'add(5, 10)' },
        { id: 'c6-opt2', code: 'add(5 10)' },
        { id: 'c6-opt3', code: 'add 5, 10' },
    ],
    solution: ['c6-opt1'],
    blanks: 1,
  },
  {
    title: 'Level 7: Return Values',
    description: 'Functions can return a value. Complete the function to return the product of two numbers.',
    concept: {
        title: 'Return Values',
        explanation: 'A function can send a value back to the code that called it. This is called a "return value". The `return` keyword is used to specify what value the function should send back.',
    },
    codeTemplate: [
        '#include <stdio.h>',
        '',
        'int multiply(int a, int b) {',
        '    ',
        null,
        ';',
        '}',
        '',
        'int main() {',
        '    int result = multiply(3, 4);',
        '    printf("Result: %d\\n", result);',
        '    return 0;',
        '}',
    ],
    options: [
        { id: 'c7-opt1', code: 'return a * b' },
        { id: 'c7-opt2', code: 'print(a * b)' },
        { id: 'c7-opt3', code: 'a * b' },
    ],
    solution: ['c7-opt1'],
    blanks: 1,
  },
  {
    title: 'Level 8: While Loops',
    description: 'A `while` loop continues as long as a condition is true. Print numbers from 1 to 3.',
    concept: {
        title: 'While Loops',
        explanation: 'A `while` loop repeatedly executes a block of code as long as a given condition remains true. It\'s useful when you don\'t know exactly how many times you need to loop.',
    },
    codeTemplate: [
        '#include <stdio.h>',
        '',
        'int main() {',
        '    int i = 1;',
        '    ',
        null,
        ' {',
        '        printf("%d\\n", i);',
        '        ',
        null,
        ';',
        '    }',
        '    return 0;',
        '}',
    ],
    options: [
        { id: 'c8-opt1', code: 'while (i <= 3)' },
        { id: 'c8-opt2', code: 'i++' },
        { id: 'c8-opt3', code: 'while (i < 3)' },
        { id: 'c8-opt4', code: 'i = i + 1' },
    ],
    solution: ['c8-opt1', 'c8-opt2'],
    blanks: 2,
  },
  {
    title: 'Level 9: Arrays',
    description: 'Arrays store multiple values. Access and print the second element of the array.',
    concept: {
        title: 'Arrays',
        explanation: 'An array is a collection of similar data types stored in contiguous memory locations. You can access elements in an array using an index, starting from 0 for the first element.',
    },
    codeTemplate: [
        '#include <stdio.h>',
        '',
        'int main() {',
        '    int numbers[] = {10, 20, 30};',
        '    printf("Element: %d\\n", ',
        null,
        ');',
        '    return 0;',
        '}',
    ],
    options: [
        { id: 'c9-opt1', code: 'numbers[1]' },
        { id: 'c9-opt2', code: 'numbers[2]' },
        { id: 'c9-opt3', code: 'numbers.get(1)' },
    ],
    solution: ['c9-opt1'],
    blanks: 1,
  },
  {
    title: 'Level 10: Pointers',
    description: 'Pointers store memory addresses. Declare a pointer to an integer `x`.',
    concept: {
        title: 'Pointers',
        explanation: 'A pointer is a variable that stores the memory address of another variable. They are a powerful feature in C for managing memory directly. A `*` is used to declare a pointer and to dereference it (get the value at the address).',
    },
    codeTemplate: [
        '#include <stdio.h>',
        '',
        'int main() {',
        '    int x = 10;',
        '    ',
        null,
        ' = &x;',
        '    printf("Value via pointer: %d\\n", *ptr);',
        '    return 0;',
        '}',
    ],
    options: [
        { id: 'c10-opt1', code: 'int *ptr' },
        { id: 'c10-opt2', code: 'pointer ptr' },
        { id: 'c10-opt3', code: 'int ptr' },
    ],
    solution: ['c10-opt1'],
    blanks: 1,
  },
];
